CREATE TABLE NAVIGATOR(
    NAV_ID        VARCHAR(64)  NOT NULL,
    NAV_ROW       INT          NOT NULL,
    NAV_COL       INT          NOT NULL,
    NAV_NAME      VARCHAR(64)  NOT NULL,
    NAV_URL       VARCHAR(512),
    NAV_SEPARATOR VARCHAR(1)   DEFAULT '0',
    PRIMARY KEY(NAV_ID)
);

CREATE TABLE QUERY(
    QRY_ID        VARCHAR(64)  NOT NULL,
    QRY_KEY       VARCHAR(64)  NOT NULL,
    QRY_NAME      VARCHAR(128) NOT NULL,
    QRY_SQL       CLOB         NOT NULL,
    QRY_VIEW      VARCHAR(64)  NOT NULL,
    QRY_AUTHOR    VARCHAR(64)  DEFAULT '',
    QRY_MODIFIED  BIGINT       NOT NULL,
    PRIMARY KEY(QRY_ID)
);
CREATE UNIQUE INDEX UQ_QUERY_QRY_KEY ON QUERY (QRY_KEY);

CREATE TABLE WIDGET(
    WGT_ID        VARCHAR(64)  NOT NULL,
    WGT_TYPE      VARCHAR(64)  NOT NULL,
    WGT_POSITION  INT          NOT NULL,
    QRY_ID        VARCHAR(64)  NOT NULL,
    PRIMARY KEY(WGT_ID)
);
CREATE UNIQUE INDEX UQ_WIDGET_WGT_POS ON WIDGET (WGT_POSITION);
